### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported when running Node 18

### ISSUE THREAD

**Issue by Rush** [webpack-contrib/node-loader#82]
It happens when running on Node 18

```
Module build failed (from ../node_modules/node-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at getHashDigest (/code/nexus/node_modules/node-loader/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /code/nexus/node_modules/node-loader/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/code/nexus/node_modules/node-loader/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/code/nexus/node_modules/node-loader/dist/index.js:21:49)
```

Workaround:
```
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by alexander-akait** [comment]
Please reinstall deps, there is a fix https://github.com/webpack/loader-utils/tree/v2.0.2 to support md4 for new Node.js versions

**Comment by Rush** [comment]
Thank you, solved
